name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Default Scheme
        run: |
          cd UpkeepiOS
          scheme_list=$(xcodebuild -list -json)
          default_scheme=$(echo "$scheme_list" | jq -r '.project.schemes[0]')
          echo "default=$default_scheme" >> $GITHUB_ENV
          echo Using default scheme: $default_scheme

      - name: Build
        run: |
          cd UpkeepiOS
          xcodebuild clean build analyze -scheme "${{ env.default }}" -project "Upkeep.xcodeproj"
